name: Deploy to EC2 (Amazon Linux 2)

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest

    steps:
      - name: excuting remote ssh commands
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.EC2_HOST }} 
          username: ${{ secrets.EC2_USER }} 
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          port: 22
          script: | 
            # 기존 컨테이너가 있다면 종료 및 삭제
            cd ~/salguy/APP
            git pull origin main
            pip install -r requirements.txt
            pm2 restart main.py

            echo "Deployment completed successfully"
